### PR TITLE
Pagination Bug : Page has no data and freezes from next actions

### LINKED ISSUE #428: Pagination Bug : Page has no data and freezes from next actions
**Describe the bug**
When a user searches for a patient and presses the back button the pagination is distorted

**To Reproduce**
Steps to reproduce the behaviour:
1. Scroll back and forth the pages
2. Search for a patient e.g Cook
3.  Enter profile
4. Press the Back button
5. Press Next

**Expected behaviour**

- [x] We should properly  handle /Clear the back stack appropriately 
- [x] Make sure that when the back is pressed either clear search and go back to the previous context and then show the patient list with the appropriate date  

**Screenshots**

**Smartphone (please complete the following information):**
Emulator and Physical devices 

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by syedowaisali90**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #428 

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Release | Other) 

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by pld — DISMISSED** [review]

File: android/app/src/test/java/org/smartregister/fhircore/fragment/PatientListFragmentTest.kt [hunk 1]
```diff
@@ -174,14 +165,7 @@ class PatientListFragmentTest : FragmentRobolectricTest() {
       Pair(mutableListOf(patient), Pagination(totalItems = 1, pageSize = 5, currentPage = 1))
     )
     val container = getView<LinearLayout>(R.id.empty_list_message_container)
-    val buttonLayout =
```
Comment (pld) [inline android/app/src/test/java/org/smartregister/fhircore/fragment/PatientListFragmentTest.kt:177]: can you please add some new tests to cover as much as possible of `PatientListFragment`, this shows the uncovered lines, https://coveralls.io/builds/41754631/source?filename=src%2Fmain%2Fjava%2Forg%2Fsmartregister%2Ffhircore%2Ffragment%2FPatientListFragment.kt

**Review by pld — CHANGES_REQUESTED** [review]

**Review by pld — APPROVED** [review]
