### PR TITLE
Online login with expired refresh token should not render PIN view

### LINKED ISSUE #2424: Bug: Online login with expired refresh token should not render PIN view
**Describe the bug**
PIN login immediately redirects to credentials login page if app was offline

**To Reproduce**
1. Login into the app when online
2. Set device to Offline mode e.g. by Setting Airplane mode on
3. Log out
4. Wait for some time till the refresh token expires (depends on Keycloak configuration)
5. Set Airplane mode off
6. Login into the app

**Expected behavior**
If device was offline and we launch it it when Online it should render the credentials page instead of the PIN login page

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 3 XL emulator]
 - Version 31

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by ndegwamartin**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #2424

**Engineer Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [x] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/login/LoginViewModel.kt [hunk 1]
```diff
@@ -304,4 +304,6 @@ constructor(
         .build()
     workManager.enqueue(oneTimeWorkRequest)
   }
+
+  fun isCurrentRefreshTokenExpired() = !tokenAuthenticator.isCurrentRefreshTokenActive()
```
Comment (ellykits) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/login/LoginViewModel.kt:308]: Is this one-liner function necessary? Looks like it's only used in one place.

**Review by ellykits — DISMISSED** [review]

**Review by ellykits — APPROVED** [review]
