### PR TITLE
Fix code coverage for Robolectric tested classes

### LINKED ISSUE #259: Code coverage report configuration
We need to fix code coverage reports not being collected on some classes. We also need to add JUnit 5 support

- [x] Fix coverage reporting missing from Jacoco
- [x] Upgrade testing dependencies
- [x] Migrate to JUnit 5
- [x] Replace Powermock with MockK

### PR DESCRIPTION
**Pull request by ndegwamartin**
Fixes #259

**Type**
 Testing | Code health

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by pld — DISMISSED** [review]

File: android/app/src/test/java/org/smartregister/fhircore/util/UtilsTest.kt [hunk 1]
```diff
@@ -22,7 +22,10 @@ import org.apache.commons.lang3.time.DateUtils
 import org.joda.time.DateTime
 import org.junit.Assert
 import org.junit.Test
+import org.robolectric.annotation.Config
+import org.smartregister.fhircore.shadow.FhirApplicationShadow
 
+@Config(shadows = [FhirApplicationShadow::class])
```
Comment (ekigamba) [inline android/app/src/test/java/org/smartregister/fhircore/util/UtilsTest.kt:28]: We probably don't need this since this test does not use Robolectric/Junit4 Runner

**Review by ekigamba — CHANGES_REQUESTED** [review]

**Review by ekigamba — APPROVED** [review]
