### PR TITLE
1070 - relogin after logout

### LINKED ISSUE #1070: [eCBIS] Pin Login Set not working as it should
App: ecbis 
v.0.0.2
**Describe the bug**
- [ ] After the initial login, creation of a login page and syncing data. When the user logs out of the system, they are redirected to the main page and asked to select app afresh. 

**To Reproduce**
1. Log into the ecbis app with username and password. 
2. Set a pin for the CHA to use. 
3. Once data sync is completed, log out of the app. 
4. User is redirected to the 'select app' page. 

**Expected behavior**
When a user logs in the first time using a username and password and sets a pin when they log out of the app they should be redirected to the pin-login page. Login should then use the pin that was set both when the user is online and when offline. 

**Screenshots**
https://user-images.githubusercontent.com/58034047/154482727-784764e0-1b58-4b8f-a51b-f6871ac1ca8e.mp4

### PR DESCRIPTION
**Pull request by AbdulWahabMemon**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #1070 

**Type**
Bug fix 

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/engine/src/main/java/org/smartregister/fhircore/engine/ui/pin/PinViewModel.kt [hunk 1]
```diff
@@ -156,6 +158,8 @@ constructor(
     // _launchDialPad.value = "tel:####"
   }
 
+  // Todo: discuss with ben, whether we need user to redirect to settings or not,
```
Comment (pld) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/ui/pin/PinViewModel.kt:161]: @dubdabasoduba is there more to discuss here?

**Review by pld — APPROVED** [review]

File: android/engine/src/main/java/org/smartregister/fhircore/engine/ui/pin/PinViewModel.kt (hunk 1 above)
Comment (dubdabasoduba) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/ui/pin/PinViewModel.kt:161]: @pld not sure, @AbdulWahabMemon do you mind elaborating more on this comment. If it's not necessary please delete it. So is line `162` if all concerns have been considered.

File: android/engine/src/main/java/org/smartregister/fhircore/engine/ui/appsetting/AppSettingActivity.kt [hunk 2]
```diff
@@ -55,7 +55,9 @@ class AppSettingActivity : AppCompatActivity() {
             accountAuthenticator = accountAuthenticator
           ) { loadSuccessful: Boolean ->
             if (loadSuccessful) {
-              sharedPreferencesHelper.write(APP_ID_CONFIG, applicationId)
+              if (appSettingViewModel.rememberApp.value == true) {
```
Comment (dubdabasoduba) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/ui/appsetting/AppSettingActivity.kt:58]: @pld Because of [these](https://github.com/opensrp/fhircore/issues/1070#issuecomment-1048491483) updates. The remember me functionality is only relevant when running the app in an online setting. Does it makes sense to update the code to online for these conditions or should we remove the remember me piece completely?

File: android/engine/src/main/java/org/smartregister/fhircore/engine/util/SecureSharedPreference.kt [hunk 3]
```diff
@@ -72,6 +71,19 @@ class SecureSharedPreference @Inject constructor(@ApplicationContext val context
...
+      putString(KEY_LATEST_SESSION_TOKEN_PREFERENCE, retrieveCredentials()!!.sessionToken)
+    }
+  }
+
+  fun retrievePinCredentials(): AuthCredentials? {
+    return secureSharedPreferences
+      .getString(KEY_PIN_CREDENTIALS, null)
+      ?.decodeJson<AuthCredentials>()
+  }
+
```
Comment (dubdabasoduba) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/util/SecureSharedPreference.kt:86]: Does this code the latest change requests where we do not clear the shared preferences even after login to facilitate offline login?

**Review by dubdabasoduba — CHANGES_REQUESTED** [review]

File: android/engine/src/main/java/org/smartregister/fhircore/engine/ui/appsetting/AppSettingActivity.kt (hunk 2 above)
Comment (pld) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/ui/appsetting/AppSettingActivity.kt:58]: Is remember me a user controlled setting? So this isn't needed because it's basically always active? If the app has configured pin login to be off, would it be useful then?

File: android/engine/src/main/java/org/smartregister/fhircore/engine/ui/pin/PinViewModel.kt (hunk 1 above)
Comment (AbdulWahabMemon) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/ui/pin/PinViewModel.kt:161]: that comment I added on when Maimoona raised this concern, 
https://onaio.slack.com/archives/C02CAU7V57H/p1644845594155169
as she mentioned that questionnaire and other resources which are get sync with first app initialize can result/cause data issues.
This is the one of the point you mentioned in our last discussion around this ticket, we will decide later whether user can change application when trying relogin ( i.e : variant anc -> ecbis ) 
I am still not sure about this, but option is there too as per Pin Login tickets description, and if user is not checking rememberMe, user will be having that option when relaunch the application

**Comment by pld** [comment]
Can you please create a new issue describing this? And then in this code comment, link to that new issue

Thank you!

File: android/engine/src/main/java/org/smartregister/fhircore/engine/ui/appsetting/AppSettingActivity.kt (hunk 2 above)
Comment (dubdabasoduba) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/ui/appsetting/AppSettingActivity.kt:58]: Not really since we still need to support offline login capabilities

File: android/engine/src/main/java/org/smartregister/fhircore/engine/util/SecureSharedPreference.kt (hunk 3 above)
Comment (AbdulWahabMemon) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/util/SecureSharedPreference.kt:86]: these changes are required for pin based login

Comment (dubdabasoduba) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/util/SecureSharedPreference.kt:86]: https://github.com/opensrp/fhircore/issues/1098

**Review by dubdabasoduba — APPROVED** [review]

**Review by dubdabasoduba — APPROVED** [review]
https://github.com/opensrp/fhircore/issues/1098 Moved all the offline concerns to this issue.
