### PR TITLE
Clear replay cache once questionnaire submission event is consumed

### LINKED ISSUE #2344: Snackbar message displayed everytime user navigates to household profile after adding a member
**Describe the bug**
After a adding a new family member to a household, the `Household member has been added` snackbar message is displayed everytime user navigates to the household profile.

This snackbar message should only be displayed once after adding the new member

**To Reproduce**
1. Navigate to household register by clicking on one of the families in the household register
2. Click on the fab button on the bottom left of the screen to open the `Add household member` form
3. Fill in the form and submit
4. App navigates back to household profile where a `Household member has been added` snackbar message is displayed
5. Navigate to the household register.
6. Navigate back to the household profile
7. Note that the `Household member has been added` snackbar message is displayed again

**Expected behavior**
The `Household member has been added` snackbar message should only be displayed once after addition of a family member.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2 
 - Android version: Android 11
 - Version 30

### PR DESCRIPTION
**Pull request by Rkareko**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #2344 

**Engineer Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/quest/src/main/java/org/smartregister/fhircore/quest/event/EventBus.kt [hunk 1]
```diff
@@ -27,4 +27,6 @@ class EventBus @Inject constructor() {
   val events = _events.asSharedFlow()
 
   suspend fun triggerEvent(event: AppEvent) = _events.emit(event)
+
+  fun resetReplayCache() = _events.resetReplayCache()
```
Comment (ellykits) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/event/EventBus.kt:31]: Is it possible to have some sort of a listener to when an event has been consumed? It's easy to forget calling this function.

**Review by ellykits — CHANGES_REQUESTED** [review]

File: android/quest/src/main/java/org/smartregister/fhircore/quest/event/EventBus.kt (hunk 1 above)
Comment (ellykits) [reply android/quest/src/main/java/org/smartregister/fhircore/quest/event/EventBus.kt:31]: This means we have to call it each time an event is consumed which is a bit repetitive

Comment (ndegwamartin) [reply android/quest/src/main/java/org/smartregister/fhircore/quest/event/EventBus.kt:31]: Quick one(s), for our use case:
1. Do we expect our events to have multiple subscribers that all need to process it? 
2. Must all the events be processed or it is okay to drop some and pick the latest?
3. Do we intend to support different types of Events from this _sharedFlow_?

Comment (ellykits) [reply android/quest/src/main/java/org/smartregister/fhircore/quest/event/EventBus.kt:31]: To answer your questions @ndegwamartin 
1. Yes we may have such use case example listening to sync state events.
2. All event should be processed
3. Yes we already do other than `QuestionnaireSubmission` we will have other event types.

Comment (ndegwamartin) [reply android/quest/src/main/java/org/smartregister/fhircore/quest/event/EventBus.kt:31]: Got it, we probably need to factor in ensuring that we initialise all subscribers before any event emissions since the replay cache only stores the last event for late subscribers

**Review by ellykits — APPROVED** [review]

**Review by ellykits — APPROVED** [review]
