### PR TITLE
Fix issue #1941 [App config id throwing 503 error [intermittent Issue]

### LINKED ISSUE #1941: [Quest] App config id throwing 503 error [intermittent Issue]
**Describe the bug**
In this case of using `cha` config id, the app throws a 503 error. The HyperText Transfer Protocol (HTTP) 503 Service Unavailable server error response code indicates that the server is not ready to handle the request. Common causes are a server that is down for maintenance or that is overloaded.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the app 
2. Enter the config id 
3. Error occurs 

**Expected behaviour**
Give appropriate error message on failure or proceed to validate and move to authentication if config ID is valid 

**Screenshots**

### PR DESCRIPTION
**Pull request by SebaMutuku**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #1941  

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/engine/src/main/java/org/smartregister/fhircore/engine/ui/appsetting/AppSettingViewModel.kt [hunk 1]
```diff
@@ -144,9 +146,18 @@ constructor(
       showProgressBar.postValue(false)
     }
       .onFailure {
-        Timber.w(it)
+        Timber.i("Failed to load configs: Error [${it.localizedMessage}]")
```
Comment (ellykits) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/ui/appsetting/AppSettingViewModel.kt:149]: Use Timber.e instead. This is an error log.

**Review by ellykits — DISMISSED** [review]

File: android/engine/src/main/java/org/smartregister/fhircore/engine/ui/appsetting/AppSettingViewModel.kt (hunk 1 above)
Comment (SebaMutuku) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/ui/appsetting/AppSettingViewModel.kt]: Updated.

**Review by pld — APPROVED** [review]
