### PR TITLE
[Quest/Malawi Core] Previously completed tasks on a patient's profile randomly being reset on completion of a new task

### LINKED ISSUE #1760: [Quest/Malawi Core] Previously completed tasks on a patient's profile randomly being reset on completion of a new task
**Describe the bug**
When you complete a patient's task, on returning to their patient profile, the task gets checked off to signify that it has been completed. After you complete another task and return to the profile, in some instances all their previous tasks get reset and their check marks disappear. This doesn't always happen but it does every once in a while.

**To Reproduce**
1. Register a newly diagnosed person
2. In their profile, complete the tasks one by one
3. See if the completion of one task resets the previously entered tasks

**Expected behavior**
I expect that once a task has been completed, it remains checked off on the patient's profile until the visit is completed using the 'Finish Visit' button.

**Screenshots**
https://user-images.githubusercontent.com/90775548/197154152-81c1d337-f6b1-48e6-bf5d-51dddbcc7718.mp4

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by calmwalija**
… randomly being reset on completion of a new task

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #1760

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by LZRS — APPROVED** [review]
lgtm

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt [hunk 1]
```diff
@@ -141,10 +148,9 @@ constructor(val fhirEngine: FhirEngine, val transformSupportServices: TransformS
             val outcome = value.outcomeReference.find { x -> x.reference.contains(id) }
             if (outcome != null) {
               carePlanToUpdate = carePlan.copy()
-              carePlanToUpdate?.activity?.set(
-                index,
-                value.apply { detail.status = CarePlan.CarePlanActivityStatus.COMPLETED }
-              )
+              value.detail.status = CarePlan.CarePlanActivityStatus.COMPLETED
+              value.outcomeReference.first().reference = "Task/${task.id}"
```
Comment (LZRS) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:152]: Instead of changing first `outcomeReference`, may be it should change first matching the previous id
