### PR TITLE
🔧  Hot Fix : Correctly append PlanDefinition reference in CarePlan

### LINKED ISSUE #3383: FHIR CarePlan generator not appending
**Issue** 
The current code generates reference as `123456` instead of `PlanDefinition/123456`

**Resolved**
The PlanDefiniton reference is not correctly appended to CarePlan using StructureMap extraction against a patient. Sample code snippet from the FhirCarePlanGenerator Ln 133

```kotlin
        ?: CarePlan().apply {
          // TODO delete this section once all PlanDefinitions are using new recommended approach
          this.title = planDefinition.title
          this.description = planDefinition.description
          this.instantiatesCanonical = listOf(CanonicalType(planDefinition.asReference().reference))
          // Add the subject's Related Entity Location tag to the CarePlan
          relatedEntityLocationTags.forEach(this.meta::addTag)
        }
```

### PR DESCRIPTION
**Pull request by f-odhiambo**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #3383 

**Engineer Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/gradle/wrapper/gradle-wrapper.properties [hunk 1]
```diff
@@ -1,5 +1,7 @@
 distributionBase=GRADLE_USER_HOME
-distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-bin.zip
 distributionPath=wrapper/dists
+distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-bin.zip
+networkTimeout=10000
+validateDistributionUrl=true
```
Comment (ellykits) [inline android/gradle/wrapper/gradle-wrapper.properties:5]: Can we migrate these gradle changes to a separate PR unless the changes are needed for this fix?

File: android/gradlew [hunk 2]
```diff
@@ -1,78 +1,127 @@
-#!/usr/bin/env sh
+#!/bin/sh
```
Comment (ellykits) [inline android/gradlew:1]: Can we migrate these gradle changes to a separate PR unless the changes are needed for this fix?

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt [hunk 3]
```diff
@@ -209,7 +228,15 @@ constructor(
...
             if (definition.kind == ActivityDefinition.ActivityDefinitionKind.CAREPLAN) {
               dynamicValue.expression.expression
-                .let { fhirPathEngine.evaluate(null, input, planDefinition, subject, it) }
+                .let {
+                  fhirPathEngine.evaluate(
+                    null,
+                    input,
+                    planDefinition,
+                    subject,
+                    it,
```
Comment (ellykits) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:237]: You can use named parameters to improve code readablity.

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt [hunk 4]
```diff
@@ -255,8 +282,17 @@ constructor(
...
+              if (
+                it.status.isIn(
+                  TaskStatus.REQUESTED,
+                  TaskStatus.READY,
+                  TaskStatus.INPROGRESS,
+                )
+              ) {
+                cancelTaskByTaskId(
+                  it.logicalId,
+                  "${carePlan.fhirType()} ${carePlan.status}",
```
Comment (ellykits) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:294]: Use named parameters. These params are of the same type.

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt [hunk 5]
```diff
@@ -406,7 +445,11 @@ constructor(
             )
 
           if (resourceClosureConditionsMet) {
-            defaultRepository.updateResourcesRecursively(eventResource, subject, eventWorkFlow)
+            defaultRepository.updateResourcesRecursively(
+              eventResource,
+              subject,
+              eventWorkFlow,
```
Comment (ellykits) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:451]: Improve readability by using named params.

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt [hunk 6]
```diff
@@ -167,6 +174,18 @@ constructor(
     return if (output.hasActivity()) output else null
   }
 
+  // TODO refactor this code to remove hardcoded appended "PlanDefinition/"
```
Comment (ellykits) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:177]: Is this TODO needed with the code implementation below in place? From the implementation below this todo, you are replacing the `instantiatesCanonical` when the first item does not contain a `/`.

**Review by ellykits — CHANGES_REQUESTED** [review]

File: android/gradle/wrapper/gradle-wrapper.properties (hunk 1 above)
Comment (f-odhiambo) [reply android/gradle/wrapper/gradle-wrapper.properties:5]: App does not build without upgrading

File: android/gradlew (hunk 2 above)
Comment (f-odhiambo) [reply android/gradlew:1]: Am open to this but I think even here it could suffice , but very open to migrate

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt (hunk 3 above)
Comment (f-odhiambo) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:237]: change in code were not introduced by my commit and were there from before

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt (hunk 4 above)
Comment (f-odhiambo) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:294]: change in code were not introduced by my commit and were there from before

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt (hunk 5 above)
Comment (f-odhiambo) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:451]: change in code were not introduced by my commit and were there from before

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt (hunk 6 above)
Comment (f-odhiambo) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:177]: This is a TODO because the Instaciates Canonical is not limited to a PlanDef but also other resources , but for our usecase we mostly generate a CarePlan based on a defined PD see more here https://hl7.org/fhir/R4B/careplan-definitions.html#CarePlan.instantiatesCanonical

File: android/gradle/wrapper/gradle-wrapper.properties (hunk 1 above)
Comment (ndegwamartin) [reply android/gradle/wrapper/gradle-wrapper.properties:5]: Yeah lets remove the gradlew stuff from this PR. CI should build fine.

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt (hunk 4 above)
Comment (ndegwamartin) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:294]: See my previous comment

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt (hunk 5 above)
Comment (ndegwamartin) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:451]: See previous comment

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt (hunk 6 above)
Comment (ndegwamartin) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:177]: Seems acceptable for now since this is only temporary. 

In line with this please link the ticket to track the actual issue/fix on this comment so that it is easy to know when the code can be stripped .  Something like :

```java
// TODO refactor this code to remove hardcoded appended PlanDefinition/  when this ticket is closed https://github.com/google/android-fhir/issues/<some ticket id>
```

**Comment by ndegwamartin** [comment]
Also in line with the internal conversation we can mark this method here with with the `@Deprecated` annotation cc @pld  https://github.com/opensrp/fhircore/blob/70a8bc1c7ddcdc32b1058add45ac678e2b2be843/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt#L171


You can add this:

```kotlin
  @Deprecated(
    message = "This function is deprecated, use workflowCarePlanGenerator.applyPlanDefinitionOnPatient() instead",
    replaceWith = ReplaceWith("workflowCarePlanGenerator.applyPlanDefinitionOnPatient()"),
    level = DeprecationLevel.WARNING
  )
  private suspend fun liteApplyPlanDefinitionOnPatient( ...
  ```

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt (hunk 6 above)
Comment (f-odhiambo) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:177]: OK

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt (hunk 5 above)
Comment (f-odhiambo) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:451]: OK

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt (hunk 3 above)
Comment (f-odhiambo) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:237]: Done https://github.com/opensrp/fhircore/issues/3386

File: android/gradle/wrapper/gradle-wrapper.properties (hunk 1 above)
Comment (f-odhiambo) [reply android/gradle/wrapper/gradle-wrapper.properties]: Reverted

**Review by f-odhiambo — COMMENTED** [review]
Resolved comments from PR rewview

File: android/gradlew (hunk 2 above)
Comment (f-odhiambo) [reply android/gradlew]: Done

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt [hunk 7]
```diff
@@ -167,7 +174,24 @@ constructor(
...
+  @VisibleForTesting
+  fun invokeCleanPlanDefinitionCanonical(carePlan: CarePlan) =
+    carePlan.cleanPlanDefinitionCanonical()
+
   /** Implements OpenSRP's $lite version of CarePlan & Tasks generation via StructureMap(s) */
+  @Deprecated(
+    message = "This function is deprecated, use workflowCarePlanGenerator.applyPlanDefinitionOnPatient() instead",
+    replaceWith = ReplaceWith("workflowCarePlanGenerator.applyPlanDefinitionOnPatient()"),
+    level = DeprecationLevel.WARNING
+  )
```
Comment (dubdabasoduba) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:194]: @f-odhiambo did we agree on deprecating this SM approach for CarePlan generation?

**Review by dubdabasoduba — CHANGES_REQUESTED** [review]

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt [hunk 8]
```diff
@@ -131,8 +137,7 @@ constructor(
         .map { it.resource }
         .firstOrNull()
         ?: CarePlan().apply {
-          // TODO delete this section once all PlanDefinitions are using new
-          // recommended approach
+          // TODO delete this section once all PlanDefinitions are using new recommended approach
```
[the remark this answers is not in the document]
Comment (f-odhiambo) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:140]: @dubdabasoduba This comment was left I believe by Maimoona alluding to when $apply would be ready

[the remark this answers is not in the document]
Comment (f-odhiambo) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:140]: Maimoona left this comment in anticipation of when $apply would take over

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt (hunk 7 above)
Comment (f-odhiambo) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt]: @dubdabasoduba See more here https://onaio.slack.com/archives/C01JEDB8WTU/p1721156393259029

**Review by dubdabasoduba — APPROVED** [review]

**Review by ellykits — APPROVED** [review]
