### PR TITLE
Fixes the app showing a "Sync Complete" message even on sync failure

### LINKED ISSUE #2575: The app shows a "Sync Complete" toaster even if sync failed
**Describe the bug**
- Currently, the application would emit a _Sync Complete_ toaster even if the sync didn't complete successfully. 
- This is confusing to the users and might lead to data loss in case users deleted the app based on the toaster. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Application
2. Generate some invalid data that can't sync to the server. 
3. Click on the sync icon 
4. Wait and see the response after it fails

**Expected behaviour**
- [ ] _Sync Complete_ Should only be emitted if all the required data has been synced to and from the sync.

### PR DESCRIPTION
**Pull request by ndegwamartin**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Closes #2575 

**Additionally Includes:**
- Fix Missing Manifest Resources on Setup
- Enhance Sync Progress View logic
- Fix NON PROXY flag incorrect state in dev mode
- Improve UX when launching Insights

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by ellykits — APPROVED** [review]

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/appsetting/AppSettingViewModel.kt [hunk 1]
```diff
@@ -129,15 +132,20 @@ constructor(
...
+                        profileConfig
+                          ?.fhirResource
+                          ?.dependentResourceTypes(
+                            patientRelatedResourceTypes,
+                          )
+                      } else {
+                        registerConfig.fhirResource.dependentResourceTypes(
+                          patientRelatedResourceTypes,
+                        )
+                      }
```
Comment (pld) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/appsetting/AppSettingViewModel.kt:148]: because we are ignoring unknown keys, as it was written it always decodes as RegisterConfiguration

Comment (ndegwamartin) [reply android/quest/src/main/java/org/smartregister/fhircore/quest/ui/appsetting/AppSettingViewModel.kt:148]: with the new implementation looks like we might experience a crash if registerConfig was actually ever null

Comment (pld) [reply android/quest/src/main/java/org/smartregister/fhircore/quest/ui/appsetting/AppSettingViewModel.kt:148]: maybe, it would be a pre-existing issue since that's the same as config getting set to null in the previous version, I think we have a test for that, but it might be passing b/c of mocks
