### PR TITLE
Clear text to re-generate it from SDK

### LINKED ISSUE #2994: HTML in Questionnaire is not working in edit mode
**Describe the bug**
HTML can exists in `Questionnaire.item.text`, in opening the questionnaire using edit mode, the HTML styling won't appear on the screen. But it works for default mode.

**To Reproduce**
1. Have a Questionnaire with item text that has HTML
2. Submit that Questionnaire in default mode, so you will have the QR saved, e.g. Add Patient
3. Open that Questionnaire in edit mode, e.g. Registration Info
4. You will see the Questionnaire's HTML styling won't appear on the text

**Expected behavior**
The HTML styling should appear in edit mode

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A2 emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**
- Not all HTML tags works on Android SDK, so please test this using something common like `<b>` or `<i>`
- Found this bug on Engage where we use a lot of HTML texts for styling

### PR DESCRIPTION
**Pull request by FikriMilano**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #2994 

Clear text from QuestionnaireResponse, so that the SDK (SDC [QuestionnaireViewModel](https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt#L862)) will re-generate a new text with HTML.

**Engineer Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [x] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireActivity.kt [hunk 1]
```diff
@@ -203,7 +204,11 @@ class QuestionnaireActivity : BaseMultiLanguageActivity() {
           )
 
         val questionnaireResponse =
-          QuestionnaireResponse().apply { item = latestQuestionnaireResponse?.item }
+          QuestionnaireResponse().apply {
+            item = latestQuestionnaireResponse?.item
+            clearText() // Clearing the text prompts the SDK to re-process the content, which
+            // include HTMLs
```
Comment (pld) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireActivity.kt:210]:
```suggestion
            // Clearing the text prompts the SDK to re-process the content, which includes HTML
            clearText()
```

**Review by pld — APPROVED** [review]
