### PR TITLE
Pin login redirection issue fix

### LINKED ISSUE #1112: V.0.0.3 - app closure when using previously set pin
eCBIS: v.0.0.3
**Describe the bug**
V.0.0.3 
- [x] When I upgraded app from v 0.0.2 to 0.0.3, the app was able to redirect me to the pin login page. However, the app crashed the moment I entered the pin previously set. This is happening for the first 3 or so times I try to log in. 
Other observations: this did not occur when I used the password and set the pin login again. 
- [x] When I logged in using the password, I was prompted to set pin again, even though I had set this in the previous logins. 

**Expected behavior**
- [x] When a user upgrades from any previous version of the app, if they had set the pin for login, they should be redirected to the pin log-in page. The app should not crash if the user enters a previously set pin. 
- [x] If a user opts to use a password after setting the pin, once they are redirected to the username/password page, they will be required to enter the username and password. Once they enter the correct username and password, they are redirected to the register main page. 
image

### PR DESCRIPTION
**Pull request by RaaziaTarique**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #1112

**Type**
Choose one: Bug fix

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by AbdulWahabMemon — COMMENTED** [review]
Lgtm

**Review by dubdabasoduba — APPROVED** [review]

File: android/engine/src/test/java/org/smartregister/fhircore/engine/ui/login/LoginActivityTest.kt [hunk 1]
```diff
@@ -94,6 +94,19 @@ class LoginActivityTest : ActivityRobolectricTest() {
...
+  @Test
+  fun testNavigateToHomeShouldVerifyExpectedIntentWhenPinExists() {
+    coEvery { accountAuthenticator.hasActivePin() } returns true
+    coEvery { sharedPreferencesHelper.read(FORCE_LOGIN_VIA_USERNAME, false) } returns true
+    coEvery { sharedPreferencesHelper.read("shared_pref_theme", "") } returns ""
+    coEvery { sharedPreferencesHelper.write(FORCE_LOGIN_VIA_USERNAME, false) } returns Unit
+    val loginConfig = loginViewConfigurationOf(enablePin = true)
+    loginViewModel.updateViewConfigurations(loginConfig)
+    loginViewModel.navigateToHome()
+
```
Comment (AbdulWahabMemon) [inline android/engine/src/test/java/org/smartregister/fhircore/engine/ui/login/LoginActivityTest.kt:106]: AssertFalse for FORCE_LOGIN_VIA_USERNAME

**Review by AbdulWahabMemon — APPROVED** [review]
