### PR TITLE
[MWCore] Refactor search

### LINKED ISSUE #1767: [Quest/Malawi Core] Refactor the search to make it more functional
**Name of feature to enhance**
Search

**Description of feature**
Allows user to find patients using their name or unique identifier

**Describe the enhancement**
Currently there are a number of challenges with the search:
- For the search to work well, the user needs to do an initial search which takes too long. The subsequent searches will then return immediate results. This was implemented in this [PR](https://github.com/opensrp/fhircore/pull/1669).
- If the app crashes, the user needs to perform this long initial search once again.
- A newly registered patient is not found when searched.

Ideally, the refactored search should eradicate these challenges. On first search, the search results should be immediate whether the patient was newly registered or not.

### PR DESCRIPTION
**Pull request by sevenreup**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #1767

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/register/dao/HivRegisterDao.kt [hunk 1]
```diff
@@ -101,6 +103,38 @@ constructor(
...
+            modifier = StringFilterModifier.CONTAINS
+            value = nameQuery
+          }
+        )
+        filter(Patient.ACTIVE, { value = of(true) })
+        filter(Patient.GENDER, { value = of(CodeType("male")) }, { value = of(CodeType("female")) })
+        sort(Patient.NAME, Order.ASCENDING)
+        count = PaginationConstant.DEFAULT_PAGE_SIZE
+        from = currentPage * PaginationConstant.DEFAULT_PAGE_SIZE
+      }
```
Comment (LZRS) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/register/dao/HivRegisterDao.kt:125]: Seems like this does not take into filtration through the `identifier` and ART number as previously done [here](https://github.com/opensrp/fhircore/blob/7d8644c9dd1dee066a67d7a55a375f77987e3f21/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/patient/register/PatientRegisterViewModel.kt#L182)

**Review by LZRS — CHANGES_REQUESTED** [review]

**Review by LZRS — APPROVED** [review]
LGTM
