### PR TITLE
Fix StructureMap missing app crash

### LINKED ISSUE #1848: [Quest] Provide error-handling if StructureMap has an error during the extraction process
**Name of feature to enhance**
Provide error handling if StructureMap has an error during the extraction process

**Description of feature**
Add a mechanism to prevent a crash when there is an issue with the StructureMap and also log/provide feedback for action

**Describe the enhancement**
- [x] 1. Alert user if an error was encountered 
- [x] 2. Log the details in the app for debugging / troubleshooting purposes

### PR DESCRIPTION
**Pull request by SebaMutuku**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #1848 

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt [hunk 1]
```diff
@@ -322,6 +322,7 @@ constructor(
         composition
           .retrieveCompositionSections()
           .groupBy { it.focus.reference?.split(TYPE_REFERENCE_DELIMITER)?.firstOrNull() ?: "" }
+          .asSequence()
```
Comment (ellykits) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt:325]: This can be moved before groupBy

File: android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/ActionConfig.kt [hunk 2]
```diff
@@ -41,7 +41,7 @@ data class ActionConfig(
 ) {
   fun paramsBundle(computedValuesMap: Map<String, Any> = emptyMap()): Bundle =
     Bundle().apply {
-      params.filter { !it.paramType?.name.equals(PREPOPULATE_PARAM_TYPE) }.forEach {
+      params.asSequence().filter { !it.paramType?.name.equals(PREPOPULATE_PARAM_TYPE) }.forEach {
```
Comment (ellykits) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/ActionConfig.kt:44]: I do not think this is really necessary here, there is only one operation.

File: android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt [hunk 3]
```diff
@@ -375,9 +380,10 @@ constructor(
       if (fhirPathExpression.isEmpty()) {
         return emptyList()
       }
-      return resources?.filter {
-        fhirPathDataExtractor.extractValue(it, fhirPathExpression).toBoolean()
-      }
+      return resources
+        ?.asSequence()
```
Comment (ellykits) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt:384]: I don't think a sequence will add any performance improvement here there is only one filter operation. Collecting result for long Lists is not performant on a sequence.

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt [hunk 4]
```diff
@@ -192,8 +192,10 @@ constructor(
       if (carePlan.status == CarePlan.CarePlanStatus.COMPLETED)
         carePlan
           .activity
+          .asSequence()
           .flatMap { it.outcomeReference }
           .filter { it.reference.startsWith(ResourceType.Task.name) }
+          .toList()
```
Comment (ellykits) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:198]: Why are we introducing this lambda here? The return type for a filter operation is already a list. This `toList` is redundant and will impact the performance of the operations

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskExpireUtil.kt [hunk 5]
```diff
@@ -70,7 +70,9 @@ constructor(@ApplicationContext val appContext: Context, val fhirEngine: FhirEng
           count = tasksCount
           sort(Task.AUTHORED_ON, Order.ASCENDING)
         }
+        .asSequence()
         .filter { it.isPastExpiry() }
+        .toList()
```
Comment (ellykits) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskExpireUtil.kt:75]: Here we have a stateful operation happening on each item of a list, so using a sequence here is not ideal. So converting this to a list is not required. See [Working with stateless/stateful operations](https://typealias.com/guides/when-to-use-sequences/)

File: android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/MeasureExtensions.kt [hunk 6]
```diff
@@ -117,5 +117,7 @@ suspend inline fun <reified R : Resource> retrievePreviouslyGeneratedMeasureRepo
       filter(MeasureReport.MEASURE, { value = measureUrl })
       operation = queryOperation
     }
+    .asSequence()
     .filter { it.period.start.formatDate(SDF_YYYY_MM_DD) == startDateFormatted }
+    .toList()
```
Comment (ellykits) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/MeasureExtensions.kt:122]: Generally I do not think we need to use a sequence when we eventually need to convert something back to a collection so this usage is not adding any performance improvement.

File: android/engine/src/test/java/org/smartregister/fhircore/engine/sync/SyncBroadcasterTest.kt [hunk 7]
```diff
@@ -136,16 +136,20 @@ class SyncBroadcasterTest : RobolectricTest() {
...
-      Assert.assertTrue(syncParam[it]!!.containsKey("_count"))
-    }
+    syncParam
+      .keys
+      .asSequence()
+      .filter { it.isIn(ResourceType.Binary, ResourceType.StructureMap) }
+      .forEach { Assert.assertTrue(syncParam[it]!!.containsKey("_count")) }
 
-    syncParam.keys.filter { it.isIn(ResourceType.Patient) }.forEach {
+    syncParam.keys.asSequence().filter { it.isIn(ResourceType.Patient) }.forEach {
```
Comment (ellykits) [inline android/engine/src/test/java/org/smartregister/fhircore/engine/sync/SyncBroadcasterTest.kt:145]: Using as sequence here is not useful. You need to check the kind of operations that are used after the sequence. In this case we filter then run for each statement so no impact at all.

File: android/geowidget/src/main/java/org/smartregister/fhircore/geowidget/screens/GeoWidgetViewModel.kt [hunk 8]
```diff
@@ -73,8 +73,10 @@ constructor(val defaultRepository: DefaultRepository, val dispatcherProvider: Di
       }
 
     val familiesWithLocations =
-      defaultRepository.fhirEngine
+      defaultRepository
+        .fhirEngine
         .search<Group> { filter(Group.TYPE, { value = of(coding) }) }
+        .asSequence()
```
Comment (ellykits) [inline android/geowidget/src/main/java/org/smartregister/fhircore/geowidget/screens/GeoWidgetViewModel.kt:79]: Sequence not useful here for single operation

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt [hunk 9]
```diff
@@ -118,7 +118,9 @@ constructor(
   }
 
   fun retrieveIconsAsBitmap() {
-    navigationConfiguration.clientRegisters
+    navigationConfiguration
+      .clientRegisters
+      .asSequence()
```
Comment (ellykits) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt:123]: sequence not useful for simple operation

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt [hunk 10]
```diff
@@ -239,7 +241,7 @@ constructor(
     countsMap: SnapshotStateMap<String, Long>
   ) {
     // Set count for registerId against its value. Use action Id; otherwise default to menu id
-    this.filter { it.showCount }.forEach { menuConfig ->
+    this.asSequence().filter { it.showCount }.forEach { menuConfig ->
```
Comment (ellykits) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt:244]: Sequence not useful for simple operation like `filter` and `forEach`

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/profile/ProfileViewModel.kt [hunk 11]
```diff
@@ -262,6 +263,7 @@ constructor(
               )
               .toBoolean()
           }
+          ?.toList()
```
Comment (ellykits) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/profile/ProfileViewModel.kt:266]: Is this toList() necessary for the map operation below? if that is the case then I do not think it is of best interest to use a sequence here.

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireActivity.kt [hunk 12]
```diff
@@ -101,11 +101,14 @@ open class QuestionnaireActivity : BaseMultiLanguageActivity(), View.OnClickList
...
-          !it.value.contains(STRING_INTERPOLATION_PREFIX)
-      }
+      actionParams
+        .asSequence()
+        .filter {
+          it.paramType == ActionParameterType.PREPOPULATE &&
+            !it.value.isNullOrEmpty() &&
+            !it.value.contains(STRING_INTERPOLATION_PREFIX)
+        }
+        .toList()
```
Comment (ellykits) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireActivity.kt:111]: Is this `toList` necessary? We only have a single filter operation in this sequence.

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt [hunk 13]
```diff
@@ -177,7 +177,7 @@ constructor(
     }
 
     viewModelScope.launch(dispatcherProvider.io()) {
-      questionnaire.useContext.filter { it.hasValueCodeableConcept() }.forEach {
+      questionnaire.useContext.asSequence().filter { it.hasValueCodeableConcept() }.forEach {
```
Comment (ellykits) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt:180]: I do no think there will be any performance improvements using a sequence here.

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/MeasureReportViewModel.kt [hunk 14]
```diff
@@ -538,7 +539,9 @@ constructor(
         // the observations would have key as coding.code=populationId and value as codeableConcept
         observations
           .groupBy { it.codingOf(POPULATION_OBS_URL)?.display }
+          .asSequence()
           .filter { it.key.isNullOrBlank().not() }
+          .toList()
```
Comment (ellykits) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/MeasureReportViewModel.kt:544]: Is this toList() necessary? Sequence is not performant when you collect the result

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/BottomScreenSection.kt [hunk 15]
```diff
@@ -51,7 +51,7 @@ fun BottomScreenSection(
   ) {
     val navBackStackEntry by navController.currentBackStackEntryAsState()
     val currentRoute = navBackStackEntry?.destination?.id
-    mainNavigationScreens.filter { it.showInBottomNav }.forEach { navigationScreen ->
+    mainNavigationScreens.asSequence().filter { it.showInBottomNav }.forEach { navigationScreen ->
```
Comment (ellykits) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/BottomScreenSection.kt:54]: I do not think there will be any performance improvement using a sequence here for just the `filter` and `forEach` operations.

File: android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt [hunk 16]
```diff
@@ -214,10 +214,15 @@ constructor(
             facts.getFact(relatedResourceKey).value as List<Resource>
           else emptyList()
 
-      return value.filter {
-        resource.logicalId ==
-          fhirPathDataExtractor.extractValue(it, referenceFhirPathExpression).extractLogicalIdUuid()
-      }
+      return value
+        .asSequence()
```
Comment (ellykits) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt:218]: Using a sequence here is not useful when we eventually collect the results in a list.

**Review by ellykits — CHANGES_REQUESTED** [review]

**Comment by ellykits** [comment]
Kindly review this [Working with sequences](https://typealias.com/guides/when-to-use-sequences/) especially the section that addresses stateless and stateful operations.

**Comment by pld** [comment]
The goal of using asSequence here and other places, and I'm not sure it's the correct tool, is to prevent multiple passes over the array, explicitly having a conditional in a loop for the filter would work too, not sure which is best

**Comment by ellykits** [comment]
I understand the usage. There are scenarios where using a sequence improves performance however not in all cases.

File: android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt (hunk 1 above)
Comment (SebaMutuku) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt:325]: @ellykits Adding `asSequence()` before `groupBy` is redudant. You have a look.

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt (hunk 4 above)
Comment (SebaMutuku) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt:198]: @ellykits we can have a discussion about this.

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskExpireUtil.kt (hunk 5 above)
Comment (SebaMutuku) [reply android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskExpireUtil.kt:75]: Maybe we can discuss more about this on a call or huddle.
Here's a sample 
``` kotlin  
val result = collectionOf12Items
    .asSequence()
    .map { it.toString() }
    .toList() 
```

**Comment by pld** [comment]
> I understand the usage. There are scenarios where using a sequence improves performance however not in all cases.

cool sequence isn't what I see as the important part, single pass is the important part, but maybe there's a pre-compilation or some other reason single pass isn't that important, I haven't seen literature on that

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireActivity.kt (hunk 12 above)
Comment (SebaMutuku) [reply android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireActivity.kt:111]: @ellykits it might be needed since `prePopulationParams` is of type `List<ActionParamater>`. However, using a sequence converts the collection to a `Sequence<ActionParameter>`. Maybe we can ignore the asSequence() or convert it toList() before reading elements or traversing within the collection

**Review by ellykits — APPROVED** [review]
