### PR TITLE
Fix Periodic sync jobs scheduling failure

### LINKED ISSUE #3732: Periodic sync jobs scheduling failing
**Describe the bug**
Scheduling of [periodic jobs](https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt#L448-L484) i.e `FhirTaskStatusUpdateWorker`, `FhirResourceExpireWorker`, `FhirCompleteCarePlanWorker` is failing on latest changes on `main` branch.

This is may be responsible for [this issue](https://github.com/ona-health/hisp-wdf-fhir-resources/issues/600) reported on WDF. The `FhirTaskStatusUpdateWorker` job is responsible for updating the task status to `Ready` when it's due time is reached.

**To Reproduce**
1. Do a fresh install
2. Log into the app
3. Open `App Inspection` then switch to `Background Task Inspector` tab
4. Notice that `FhirTaskStatusUpdateWorker`, `FhirResourceExpireWorker`, `FhirCompleteCarePlanWorker` jobs are missing from the `Workers` section

**Expected behavior**
`FhirTaskStatusUpdateWorker`, `FhirResourceExpireWorker`, `FhirCompleteCarePlanWorker` jobs should be visible on the `Workers` section `Background Task Inspector` tab

**Screenshots**

Image

**Smartphone (please complete the following information):**
 - Device: Pixel 2 emulator
 - Android version: Android 11
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

### PR DESCRIPTION
**Pull request by Rkareko**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #3732

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt [hunk 1]
```diff
@@ -420,31 +420,6 @@ constructor(
...
-          }
-          else -> syncBroadcaster.schedulePeriodicSync(applicationConfiguration.syncInterval)
-        }
-      } else {
-        withContext(dispatcherProvider.main()) {
-          context.showToast(context.getString(R.string.sync_failed), Toast.LENGTH_LONG)
-        }
-      }
-    }
-
```
Comment (FikriMilano) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt:447]: could you check the relevancy of this code to the periodic worker code?
and see if there's a reason on why the order of the code matters

Comment (Rkareko) [reply android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt:447]: By process of elimination, the cause has been narrowed down to this line
`syncBroadcaster.schedulePeriodicSync(applicationConfiguration.syncInterval)` .
The `why` is yet to be determined.

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt [hunk 2]
```diff
@@ -420,31 +420,6 @@ constructor(
...
-            if (
-              applicationConfiguration.usePractitionerAssignedLocationOnSync ||
-                context
-                  .retrieveRelatedEntitySyncLocationState(MultiSelectViewAction.SYNC_DATA)
-                  .isNotEmpty()
-            ) {
-              syncBroadcaster.schedulePeriodicSync(applicationConfiguration.syncInterval)
-            }
-          }
-          else -> syncBroadcaster.schedulePeriodicSync(applicationConfiguration.syncInterval)
```
Comment (FikriMilano) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt:439]: using the original code order.
try to wrap schedulePeriodicSync with viewModelScope.launch.

the original code might be hold down on this line, since schedulePeriodicSync is a suspend function and the process inside might block the next process

**Review by FikriMilano — CHANGES_REQUESTED** [review]

**Review by dubdabasoduba — APPROVED** [review]
This makes sense. NIce! catch
