### PR TITLE
Handle exceptions while performing extraction using StructureMap 

### LINKED ISSUE #1847: [Quest] Allow submitting of a Questionnaire and create a QuestionnaireResponse if StructureMap extension is not provided
**Name of feature to enhance**

**Description of feature**

**Describe the enhancement**

### LINKED ISSUE #1848: [Quest] Provide error-handling if StructureMap has an error during the extraction process
**Name of feature to enhance**
Provide error handling if StructureMap has an error during the extraction process

**Description of feature**
Add a mechanism to prevent a crash when there is an issue with the StructureMap and also log/provide feedback for action

**Describe the enhancement**
- [x] 1. Alert user if an error was encountered 
- [x] 2. Log the details in the app for debugging / troubleshooting purposes

### LINKED ISSUE #1849: [Quest] Provide error-handling if StructureMap extension is provided but the StructureMap resource is not available locally/not yet synced
**Name of feature to enhance**
Provide error handling if StructureMap extension is provided but the StructureMap resource is not available locally/not yet synced

**Description of feature**
The app should not crash upon missing StrcutureMaps for the linked Questionnaire being populated before the extraction process 

**Describe the enhancement**
On submission of a populated Questionnaire
- [x] 1. Generate a QuestionnaireReponse 
- [x] 2. If a StrucutureMap is missing log this in-app for troubleshooting and also  alert the user of the issue

### PR DESCRIPTION
**Pull request by SebaMutuku**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #1847
Fixes #1848
Fixes #1849 

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by dubdabasoduba** [comment]
@SebaMutuku Please add the appropriate PR title and link the issue in the description

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt [hunk 1]
```diff
@@ -392,21 +391,41 @@ constructor(
...
+            )
+          }
+        }
+        .onSuccess {
+          bundle = it
+          context.showToast(context.getString(R.string.structure_success))
+        }
+        .onFailure { exception ->
+          Timber.e(exception)
+          if (exception.message!!.contains("StructureMap")) {
```
Comment (pld) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt:421]: what's the exception that gets thrown here? Is there a more precise way to capture this exception? Since it's only checking for a string, couldn't this catch inappropriate exceptions

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt [hunk 2]
```diff
@@ -392,21 +391,41 @@ constructor(
...
+            context.showToast(context.getString(R.string.structure_map_missing_message))
```
Comment (pld) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt:422]: can we mention the specific structuremap it was looking for in the error?

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt [hunk 3]
```diff
@@ -392,21 +391,41 @@ constructor(
...
+          } else {
+            context.showToast(context.getString(R.string.structure_error_message))
```
Comment (pld) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt:424]: can we mention the specific structuremap that had a problem in the error?

File: android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt [hunk 4]
```diff
@@ -914,9 +917,52 @@ class QuestionnaireViewModelTest : RobolectricTest() {
...
+      context.getString(R.string.structure_map_missing_message)
+    val context = mockk<Context>(relaxed = true)
+    val questionnaire = Questionnaire()
+    val questionnaireResponse = QuestionnaireResponse()
+
+    coEvery { questionnaireViewModel.retrieveStructureMapProvider() } throws
+      NullPointerException("StructureMap on Null Object")
+
+    questionnaireViewModel.performExtraction(context, questionnaire, questionnaireResponse)
+
```
Comment (pld) [inline android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt:945]: let's check that questionnaireResponse is properly filled when missing, that can be in a separate test

File: android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt [hunk 5]
```diff
@@ -914,9 +917,52 @@ class QuestionnaireViewModelTest : RobolectricTest() {
...
+    val missingStructureMapExceptionMessage = context.getString(R.string.structure_error_message)
+    val context = mockk<Context>(relaxed = true)
+    val questionnaire = Questionnaire()
+    val questionnaireResponse = QuestionnaireResponse()
+
+    coEvery { questionnaireViewModel.retrieveStructureMapProvider() } throws
+      Exception("Failed to process resources")
+
+    questionnaireViewModel.performExtraction(context, questionnaire, questionnaireResponse)
+
```
Comment (pld) [inline android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt:959]: let's check that questionnaireResponse is properly filled when error, that can be in a separate test

**Review by pld — CHANGES_REQUESTED** [review]

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt (hunk 1 above)
Comment (SebaMutuku) [reply android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt:414]: `java.lang.NullPointerException:Attempt to invoke StructureMap on null object reference.`

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt (hunk 3 above)
Comment (SebaMutuku) [reply android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt:417]: If a `StructureMap` exists but extraction Fails, other exceptions are thrown. This is the reason the second check. To handle that.

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt (hunk 1 above)
Comment (SebaMutuku) [reply android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt:414]: Given the above, added a check to verify that exception is an instance of `NullPointerException`

File: android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt (hunk 5 above)
Comment (SebaMutuku) [reply android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt:968]: The function `performExtraction` doesn't alter the contents of `questionnaireResponse` and we don't need to add it to unit test as part of this PR.

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt (hunk 2 above)
Comment (pld) [reply android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt:418]: We want some info so that we can track down what's the causing the problem, maybe the form name would be enough, if we can only have a single structuremap tied to a form, but if we can have more then 1 structuremap tied to a form, we'd want a way to tell which

Comment (SebaMutuku) [reply android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt]: Added questionnaire name to as part of the toast message. This is because in case of exception, the function  `ResourceMapper.extract` returns an empty bundle and hence we cannot know the StructureMap name.

**Review by pld — APPROVED** [review]
