### PR TITLE
Fix profile data refresh

### LINKED ISSUE #1446: [Quest/eCBIS] - On Add Family member, refresh the patient list view to view latest addition to the family
**Describe the bug**
On Add Family member, refresh the patient list view to view the latest addition to the family

**To Reproduce**
1. Go to Household register
2. Click on  a family 
3. Add a family member 
4. Newly created member does not appear on the family member list 

**Expected behavior**
1. Go to Household register
2. Click on  a family 
3. Add a family member 
4. Refresh family member list to view newly created member as you add other family memebrs

### PR DESCRIPTION
**Pull request by ellykits**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #1446 

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt [hunk 1]
```diff
@@ -147,8 +145,6 @@ constructor(
       is AppMainEvent.UpdateSyncState -> {
         when (event.state) {
           is State.Finished, is State.Failed -> {
-            // Notify subscribers to refresh views after sync and refresh UI
-            refreshDataState.value = true
```
Comment (Rkareko) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt:151]: Could you explain why this is no longer necessary

**Comment by ellykits** [comment]
RegisterFragment is registered for sync state notification and implements
`OnSyncListener` interface. Data refresh is handled now in the `onSync`
function.

**Review by Rkareko — APPROVED** [review]
