### PR TITLE
Fix crash for uncaught exceptions when refresh token request fails

### LINKED ISSUE #2743: App crashes on SocketTimeout when refreshing Keycloak token
**Describe the bug**
Sometimes the app crashes when a sync has been initialised, and current token fails to refresh token with SocketTimeoutException

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A2 emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**

```

Exception: java.net.SocketTimeoutException: failed to connect to keycloak.d-tree.org/102.70.87.14 (port 443) from /172.57.222.126 (port 55476) after 120000ms: isConnected failed: ETIMEDOUT (Connection timed out)
       at libcore.io.IoBridge.isConnected(IoBridge.java:283)
       at libcore.io.IoBridge.connectErrno(IoBridge.java:192)
       at libcore.io.IoBridge.connect(IoBridge.java:134)
       at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
       at java.net.Socket.connect(Socket.java:621)
       at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
       at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

```

```

Caused by android.accounts.AuthenticatorException: getAuthToken failed
       at android.accounts.AccountManager.convertErrorToException(AccountManager.java:2516)
       at android.accounts.AccountManager.access$700(AccountManager.java:164)
       at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:2352)
       at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:107)
       at android.os.Binder.execTransactInternal(Binder.java:1195)
       at android.os.Binder.execTransact(Binder.java:1159)

```

### PR DESCRIPTION
**Pull request by LZRS**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #2743 

**Engineer Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [x] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/login/AccountAuthenticator.kt [hunk 1]
```diff
@@ -82,11 +80,8 @@ constructor(
             tokenAuthenticator.refreshToken(refreshToken)
           } catch (ex: Exception) {
             Timber.e(ex)
-            when (ex) {
-              is HttpException,
-              is UnknownHostException, -> ""
-              else -> throw ex
-            }
+            // any form of exception would unset token to empty, thereby forcing re-login
```
Comment (pld) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/login/AccountAuthenticator.kt:83]:
```suggestion
            // any form of exception will unset token to empty, thereby forcing re-login
```

**Review by pld — APPROVED** [review]

**Review by pld — APPROVED** [review]
