### PR TITLE
1251 family member overflow menu

### LINKED ISSUE #1251: [Quest/eCBIS] - Client profile - top right overflow menu items are missing
**Describe the bug**
When you navigate to a client profile, the top right-hand side menu has only 1 option. Thus, user:
- [x] Cannot edit the client registration details. 
- [x] Cannot mark a client as pregnant (pregnant outcome)
- [x] Cannot mark as the deceased client. 

image

**To Reproduce**
1. Log into the app. 
2. Register a female client over 15years. 
3. Navigate to their profile, and tap on the top right hand corner menu. The menu will open up. Observe the options available. 

**Expected behavior**
Once a user is registered, there should be the following options on their profile (top right menu)
- Edit info - to edit registration details for the client. Tapping on the "edit info" on the top right-hand corner menu will open up the client registration form. User should be able to edit any editable parts of the form and save them once completed. All changes updated should reflect on the client's profile. 
- Mark as deceased - this is accessed from the top-right menu. This shows on any client's profile. Tapping on this opens the person removal form. Filling this form and confirming removal will remove the person from that household's register. The name will still show on the register but marked as deceased. 
- Record pregnancy - If the client is a female over 15 years old (female of reproductive age) - the 'record pregnancy option should be displayed on the top-right menu. Tapping on this option opens the pregnancy recording form. 
image

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A2 emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**

### PR DESCRIPTION
**Pull request by roywanyaga**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #1251 partially 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/patient/profile/PatientProfileEvent.kt [hunk 1]
```diff
@@ -27,17 +28,11 @@ sealed class PatientProfileEvent {
   data class LoadQuestionnaire(val questionnaireId: String, val context: Context) :
     PatientProfileEvent()
 
-  data class OpenTaskForm(
-    val context: Context,
-    val taskFormId: String,
-    val taskId: String,
-    val patientId: String
-  ) : PatientProfileEvent()
-
```
Comment (FikriMilano) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/patient/profile/PatientProfileEvent.kt:36]: Curiosity, is there a reason to remove this?

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/patient/profile/components/ProfileActionableItem.kt [hunk 2]
```diff
@@ -61,8 +61,7 @@ import org.smartregister.fhircore.quest.ui.shared.models.PatientProfileViewSecti
 @Composable
 fun ProfileActionableItem(
   patientProfileRowItem: PatientProfileRowItem,
-  modifier: Modifier = Modifier,
-  onActionClick: (String, String) -> Unit,
```
Comment (FikriMilano) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/patient/profile/components/ProfileActionableItem.kt:65]: Another curiosity.
Why are we removing this callback?

File: android/quest/src/main/java/org/smartregister/fhircore/quest/util/mappers/ProfileViewDataMapper.kt [hunk 3]
```diff
@@ -124,7 +118,6 @@ class ProfileViewDataMapper @Inject constructor(@ApplicationContext val context:
       Task.TaskStatus.READY -> InfoColor
       Task.TaskStatus.CANCELLED -> OverdueColor
       Task.TaskStatus.FAILED -> OverdueColor
-      Task.TaskStatus.COMPLETED -> SuccessColor
```
Comment (FikriMilano) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/util/mappers/ProfileViewDataMapper.kt:127]: Another curiosity.
Why are we removing the completed state for tasks?

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/models/PatientProfileRowItem.kt [hunk 4]
```diff
@@ -19,8 +19,6 @@ package org.smartregister.fhircore.quest.ui.shared.models
 import androidx.compose.ui.graphics.Color
 
 data class PatientProfileRowItem(
-  val id: String,
-  val actionFormId: String? = null,
```
Comment (FikriMilano) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/models/PatientProfileRowItem.kt:23]: Another curiosity.
Why are we no longer need these?

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/patient/profile/components/ProfileActionableItem.kt [hunk 5]
```diff
@@ -102,26 +101,18 @@ fun ProfileActionableItem(
...
-    ActionButton(patientProfileRowItem, modifier, onActionClick)
+    ActionButton(patientProfileRowItem, modifier)
   }
 }
 
 @Composable
-private fun ActionButton(
-  patientProfileRowItem: PatientProfileRowItem,
-  modifier: Modifier,
-  onActionClick: (String, String) -> Unit
```
Comment (FikriMilano) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/patient/profile/components/ProfileActionableItem.kt:113]: Another curiosity.
Why are we also removing this callback?

**Review by FikriMilano — COMMENTED** [review]
@roywanyaga 
I had some curiosity questions. 
Other than that, it looks good.

**Review by FikriMilano — APPROVED** [review]
There seems to be another conflict.
Other than that, looks good to me.
