### PR TITLE
Current pagination buttons not at a static position (at the bottom of the page ) on the patient list view

### LINKED ISSUE #266: Current  pagination buttons not  at a static position (at the bottom of the page ) on the patient list view
**Describe the bug**
Change the styling of the pagination bar. Should be at the same position whether the list is empty or partially populated 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the patient list 
2. Add user a couple of users so that the patients per page is not equal to the pagination limit per page 
3. Check the current position  of pagination buttons on the screen

**Expected behaviour**
Have the pagination bar at the bottom of the screen as would be a bottom navigation bar

**Screenshots**
Screenshot_20210611-160106
Screenshot_20210611-160056

**Smartphone (please complete the following information):**
 - Device: Pixel 4a & Emulator 
 - Android version:11
 - Build number: RQ2A.210505.002

**Additional context**
Attached screenshots
N/A

### PR DESCRIPTION
**Pull request by syedowaisali90**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #266 

**Type**
Choose one: Bug fix

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/app/src/main/java/org/smartregister/fhircore/fragment/PatientListFragment.kt [hunk 1]
```diff
@@ -181,4 +190,31 @@ class PatientListFragment : Fragment() {
...
+    }
+
+    nextButton.visibility = if (pagination.hasNextPage()) View.GONE else View.VISIBLE
+    prevButton.visibility = if (pagination.hasPreviousPage()) View.GONE else View.VISIBLE
+    paginationView.visibility =
+      if (nextButton.visibility == View.VISIBLE || prevButton.visibility == View.VISIBLE)
+        View.VISIBLE
+      else View.GONE
+
+    if (pagination.totalPages() < 2) {
```
Comment (pld) [inline android/app/src/main/java/org/smartregister/fhircore/fragment/PatientListFragment.kt:209]: you can use a ternary here, s/t like

```kotlin
this.infoTextView.text = if (...) "" else ...
```

**Review by pld — CHANGES_REQUESTED** [review]

**Review by pld — APPROVED** [review]
