### PR TITLE
Map search bug fixes

### LINKED ISSUE #3517: Refresh map after clearing search text
**Describe the bug**
- The map on the geowidget module does not refresh after the search text is cleared.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the geowidget module and search
2. Clear the search text using the clear icon
3. See error

**Expected behaviour**
- [ ] The search box should be cleared and the map view refreshed. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A2 emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**

### LINKED ISSUE #3518: Infinite scroll error at the bottom of the screen
**Describe the bug**
- The infinite scroll seems to throw an error at the end of the screen when. The error reads `fromIndex(20) > toIndex(19)`
- This happens when trying to `subList` the search results. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Set you register to infinite scroll
2. Scroll to the last page
3. See error

**Expected behaviour**
- [ ] The register should scroll correctly without errors

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A2 emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**

### PR DESCRIPTION
**Pull request by dubdabasoduba**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #3517 
Fixes #3518 

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by ndegwamartin** [comment]
@dubdabasoduba do we need a unit test for this?

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/TopScreenSection.kt [hunk 1]
```diff
@@ -237,9 +237,7 @@ fun TopScreenSection(
             when {
               !searchQuery.isBlank() -> {
                 IconButton(
-                  onClick = {
-                    onSearchTextChanged(SearchQuery.emptyText, performSearchOnValueChanged)
-                  },
+                  onClick = { onSearchTextChanged(SearchQuery.emptyText, true) },
```
Comment (ndegwamartin) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/TopScreenSection.kt:240]: Might it be better to fix it by [passing the value true from the line here](https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/geowidget/GeoWidgetLauncherScreen.kt#L75)?

Or even consider removing it entirely since the value true is the default.

File: android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt [hunk 2]
```diff
@@ -1070,14 +1070,20 @@ constructor(
...
-            mapResourceToRepositoryResourceData(
-              relatedResourcesConfig = relatedResourcesConfig,
-              configComputedRuleValues = configComputedRuleValues,
-              secondaryResourceConfigs = secondaryResourceConfigs,
-              filterActiveResources = filterActiveResources,
-              baseResourceConfig = baseResourceConfig,
-            )
+          val maxSublistIndex = min(toIndex, searchResults.size)
+
+          if (fromIndex < maxSublistIndex) {
```
Comment (ndegwamartin) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt:1075]: We can add an edge case unit test for when we only have one item in the searchResults _(if there's none already)_

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/TopScreenSection.kt (hunk 1 above)
Comment (dubdabasoduba) [reply android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/TopScreenSection.kt:240]: @ndegwamartin We want to automatically disable search on text change for the map but enable it for the registers.  [This](https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/geowidget/GeoWidgetLauncherScreen.kt#L75) disables it for the map. 

We however want to refresh the map view every time we clear data for both the register and map views hence the `true`.  If we use `performSearchOnValueChanged` this is updated to `false`  on the link you shared earlier.

**Review by ellykits — DISMISSED** [review]
