### PR TITLE
Fix the `requested` to `ready` Task status  background job

### LINKED ISSUE #2476: Background job to move Tasks from the `requested` to `ready` ignores the Tasks with old start dates.
**Describe the bug**
- If you register a child who is 2 years old today they will have immunizations with a 2021 due date. The background job responsible for updating Task status from `requested` to `ready` filters these tasks. 

**Expected behavior**
- [ ] All tasks with a `Task.executionPeriod.start` date <= `today()` should have the `Task.status` updated to `ready`

### PR DESCRIPTION
**Pull request by dubdabasoduba**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #2476  or Closes #2476 

**Engineer Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [x] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [x] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [x] I have verified any strings visible on UI components are in the `strings.xml` file
- [x] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [x] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorker.kt [hunk 1]
```diff
@@ -65,15 +65,13 @@ constructor(
           filter(
             Task.STATUS,
             { value = of(TaskStatus.REQUESTED.toCoding()) },
-            // { value = of(Task.TaskStatus.READY.toCoding()) }, this would be handled by expiry job
-            // { value = of(Task.TaskStatus.INPROGRESS.toCoding()) },
```
Comment (pld) [inline android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorker.kt:69]: 🙏

**Review by pld — APPROVED** [review]
