### PR TITLE
Increase code coverage to >=80%

### LINKED ISSUE #855: Increase code coverage to >=80%
**Describe the Issue**

- [ ] 1. We need to add code coverage reporting for the engine/anc/eir.quest module codebase. 
- [ ] 2. Fix failing test to be able to add/improve coverage percentage 
- [x] 3. Fix ignored tests 
- [x] 4. Go through the individual tests and in some cases refactor the code.
- [ ] 5. Write more tests on the Quest module to increase its code coverage

### PR DESCRIPTION
**Pull request by owais-vd**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #855 

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Release | Other) 

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/anc/src/test/java/org/smartregister/fhircore/anc/ui/family/details/FamilyDetailScreenTest.kt [hunk 1]
```diff
@@ -135,75 +142,41 @@ class FamilyDetailScreenTest : RobolectricTest() {
...
     composeRule.onNodeWithText("Encounters".uppercase()).assertExists()
-    composeRule.onNodeWithText("Encounters".uppercase()).assertIsDisplayed()
 
     // See All encounters buttons is displayed
-    composeRule.onNodeWithText("See All".uppercase()).assertExists()
-    composeRule.onNodeWithText("See All".uppercase()).assertIsDisplayed()
-
-    // clicking see all button should call 'onSeeAllEncounterClick' method of 'listenerObjectSpy'
-    composeRule.onNodeWithText("See All".uppercase()).performClick()
-    verify { listenerObjectSpy.onSeeAllEncounterClick() }
```
Comment (ellykits) [inline android/anc/src/test/java/org/smartregister/fhircore/anc/ui/family/details/FamilyDetailScreenTest.kt:149]: Any reason why the click listener assertions were removed?

File: android/anc/src/test/java/org/smartregister/fhircore/anc/ui/family/details/FamilyDetailScreenTest.kt [hunk 2]
```diff
@@ -135,75 +142,41 @@ class FamilyDetailScreenTest : RobolectricTest() {
...
-    composeRule.onNodeWithText("Upcoming Services".uppercase()).assertIsDisplayed()
 
     // See all upcoming services button displayed
-    composeRule.onNodeWithText("See All".uppercase()).assertExists()
-    composeRule.onNodeWithText("See All".uppercase()).assertIsDisplayed()
-
-    // clicking see all button should call 'onSeeAllUpcomingServiceClick' method of
-    // 'listenerObjectSpy'
-    composeRule.onNodeWithText("See All".uppercase()).performClick()
-    verify { listenerObjectSpy.onSeeAllUpcomingServiceClick() }
```
Comment (ellykits) [inline android/anc/src/test/java/org/smartregister/fhircore/anc/ui/family/details/FamilyDetailScreenTest.kt:200]: Any reasons for removing this assertion without refactoring the actual code being tested?

**Review by ellykits — COMMENTED** [review]
Left a few comments/questions

File: android/anc/src/test/java/org/smartregister/fhircore/anc/ui/family/details/FamilyDetailScreenTest.kt (hunk 1 above)
Comment (owais-vd) [reply android/anc/src/test/java/org/smartregister/fhircore/anc/ui/family/details/FamilyDetailScreenTest.kt]: previously having some issues with a click it was not working because i moved `setContent` to the `setUp` method. Now all changes have been reverted and it's working fine

File: android/anc/src/test/java/org/smartregister/fhircore/anc/ui/family/details/FamilyDetailScreenTest.kt (hunk 2 above)
Comment (owais-vd) [reply android/anc/src/test/java/org/smartregister/fhircore/anc/ui/family/details/FamilyDetailScreenTest.kt]: https://github.com/opensrp/fhircore/pull/862#discussion_r770307434

**Review by ellykits — APPROVED** [review]
