### PR TITLE
Fix The app shows a "Sync Complete" toaster even if sync failed #2575 

### LINKED ISSUE #2575: The app shows a "Sync Complete" toaster even if sync failed
**Describe the bug**
- Currently, the application would emit a _Sync Complete_ toaster even if the sync didn't complete successfully. 
- This is confusing to the users and might lead to data loss in case users deleted the app based on the toaster. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Application
2. Generate some invalid data that can't sync to the server. 
3. Click on the sync icon 
4. Wait and see the response after it fails

**Expected behaviour**
- [ ] _Sync Complete_ Should only be emitted if all the required data has been synced to and from the sync.

### PR DESCRIPTION
**Pull request by ndegwamartin**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Relates to #2575 
- Improve UX when launching Insights
- Fix NON PROXY flag incorrect state in dev mode

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterScreen.kt [hunk 1]
```diff
@@ -108,7 +109,9 @@ fun RegisterScreen(
     }
   ) { innerPadding ->
     Box(modifier = modifier.padding(innerPadding)) {
-      if (registerUiState.isFirstTimeSync)
+      if (registerUiState.isFirstTimeSync &&
+          !registerUiState.dismissLoaderView.collectAsState(initial = false).value
```
Comment (ellykits) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterScreen.kt:113]: Can we extract this to a variable?

**Review by ellykits — CHANGES_REQUESTED** [review]
