### PR TITLE
Fix failure to open bottom sheet dialog when a newly added location is clicked

### LINKED ISSUE #3797: [Geo-Widget] Newly added location on the map does not open bottom sheet dialog when clicked
**Describe the bug**
Clicking on a newly added location on the map, whether added using the `Add Point` functionality or using a form with GPS location widget, does not open the bottom sheet dialog that displays information about the location. 

**To Reproduce**
1. Go to Map view
2. Click on `Add Point` button on the bottom left.
3. Select location to add a point using the red marker. Add the point at desired location
4. Click on the newl added point.
5. Nothing happens when the newly added location

**Expected behavior**
Clicking on a newly added location on the map should open the bottom sheet dialog

**Screenshots**
Screenshot showing how a newly added location looks like. Notice the red marker
Image

Screenshot showing the bottomsheet that is opened when a location is clicked
Image

**Smartphone (please complete the following information):**
 - Device: Pixel 2 emulator
 - Android version:Android 11

**Additional context**

### PR DESCRIPTION
**Pull request by Rkareko**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #3797 

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/geowidget/src/main/java/org/smartregister/fhircore/geowidget/screens/GeoWidgetFragment.kt [hunk 1]
```diff
@@ -378,6 +380,24 @@ class GeoWidgetFragment : Fragment() {
...
+   * indicate the location of a newly added point on the map. These red markers are not needed since
+   * FHIRCore adds icons that show the position of the location on the map. These red marker
+   * introduce a bug documented on [https://github.com/opensrp/fhircore/issues/3797]. The newly
+   * added locations do not respond to click events when the red marker is present. There is logic
+   * in the kujaku
+   * [com.mapbox.mapboxsdk.maps.MapGestureDetector.StandardGestureListener.onSingleTapConfirmed]
+   * that consumes the click events if the red marker is present.
+   *
+   * @param mapboxMap
+   */
```
Comment (FikriMilano) [inline android/geowidget/src/main/java/org/smartregister/fhircore/geowidget/screens/GeoWidgetFragment.kt:394]:
```suggestion
/**
 * Removes all map markers to prevent click event conflicts.
 * 
 * Red markers are automatically added when new points are placed on the map, but they're
 * redundant since FHIRCore renders custom location icons. More critically, these markers
 * block click events on newly added locations due to how Kujaku's gesture detector handles
 * tap events in [com.mapbox.mapboxsdk.maps.MapGestureDetector.StandardGestureDetector.onSingleTapConfirmed].
 * 
 * @param mapboxMap The MapboxMap instance to clear markers from
 */
```

**Review by FikriMilano — CHANGES_REQUESTED** [review]
