### PR TITLE
Search latest QR in PdfLauncherViewModel

### LINKED ISSUE #3493: Searching QR in the PDF generation flow does not return the latest version
**Describe the bug**
In the PDF generation, we can pass a questionnaire, the PdfFragment will search the corresponding PR, which then passed to the HtmlPopulator to be processed.

But, when search the QR, it does not necessarily return the latest one, which might return the wrong version.

https://github.com/opensrp/fhircore/blob/2601cd0fac3cfc36e4dbab90a9bb115a89aea92c/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/pdf/PdfLauncherViewModel.kt#L58

**Expected behavior**
The search should return the latest QR

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by FikriMilano**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #3493

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

File: android/quest/src/main/java/org/smartregister/fhircore/quest/ui/pdf/PdfLauncherViewModel.kt [hunk 1]
```diff
@@ -55,7 +55,9 @@ constructor(
   ): QuestionnaireResponse? {
     val searchQuery =
       createQuestionnaireResponseSearchQuery(questionnaireId, subjectId, subjectType)
-    return defaultRepository.search<QuestionnaireResponse>(searchQuery).firstOrNull()
+    return defaultRepository.search<QuestionnaireResponse>(searchQuery).maxByOrNull {
```
Comment (ellykits) [inline android/quest/src/main/java/org/smartregister/fhircore/quest/ui/pdf/PdfLauncherViewModel.kt:58]: Can you add/update the tests for this code refactor?

**Review by ellykits — CHANGES_REQUESTED** [review]

**Review by ellykits — APPROVED** [review]

**Review by ellykits — APPROVED** [review]
